//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/WebRTCAvConf-sources.jar!com/piasy/avconf/AvConfShared.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AvConfShared")
#ifdef RESTRICT_AvConfShared
#define INCLUDE_ALL_AvConfShared 0
#else
#define INCLUDE_ALL_AvConfShared 1
#endif
#undef RESTRICT_AvConfShared

#if !defined (CFAvConfShared_) && (INCLUDE_ALL_AvConfShared || defined(INCLUDE_CFAvConfShared))
#define CFAvConfShared_

#define RESTRICT_PeerConnectionClientCallback 1
#define INCLUDE_CFPeerConnectionClientCallback 1
#include "PeerConnectionClientCallback.h"

#define RESTRICT_RoomClient 1
#define INCLUDE_CFRoomClientCallback 1
#include "RoomClient.h"

#define RESTRICT_AudioDeviceManager 1
#define INCLUDE_CFAudioDeviceManagerCallback 1
#include "AudioDeviceManager.h"

@class CFAudioDevice;
@class CFConfConfig;
@class CFConfEvents;
@class CFConfEventsBase;
@class CFIceCandidate;
@class CFSessionDescription;
@class JavaUtilArrayList;
@protocol CFAudioDeviceManager;
@protocol CFCpuMonitor;
@protocol CFGuiWrapper;
@protocol CFLogger;
@protocol CFPeerConnectionClientFactory;
@protocol CFRoomClient;
@protocol CFUiTaskRunner;
@protocol JavaUtilConcurrentScheduledExecutorService;
@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@interface CFAvConfShared : CFPeerConnectionClientCallback < CFRoomClientCallback, CFAudioDeviceManagerCallback > {
 @public
  NSString *mUid_;
  CFConfConfig *mConfig_;
  CFConfEvents *mConfEvents_;
  id<JavaUtilConcurrentScheduledExecutorService> mExecutor_;
  id<CFUiTaskRunner> mUiTaskRunner_;
  id<CFAudioDeviceManager> mAudioDeviceManager_;
  id<CFCpuMonitor> mCpuMonitor_;
  id<JavaUtilMap> mPeers_;
  id<JavaUtilMap> mStats_;
  id<JavaUtilSet> mMutedPeers_;
  id<CFLogger> mLogger_;
  id<CFRoomClient> mRoomClient_;
  id<CFPeerConnectionClientFactory> mPCClientFactory_;
  id<CFGuiWrapper> mGuiWrapper_;
  jboolean mPreloaded_;
  jlong mRid_;
  id<JavaUtilList> mIceServers_;
  jboolean mResumed_;
  jboolean mVideoSourceStarted_;
  jboolean mRetrying_;
  jint mRetryDelay_;
  jint mRetries_;
  jboolean mDestroyed_;
}

#pragma mark Public

- (instancetype)initWithUid:(NSString *)uid
                  andConfig:(CFConfConfig *)config
                  andEvents:(CFConfEventsBase *)confEvents
                  andLogger:(id<CFLogger>)logger
            andUiTaskRunner:(id<CFUiTaskRunner>)uiTaskRunner
      andAudioDeviceManager:(id<CFAudioDeviceManager>)audioDeviceManager
              andCpuMonitor:(id<CFCpuMonitor>)cpuMonitor;

- (void)join:(jlong)rid;

- (void)leave;

- (void)onAudioDeviceChanged:(CFAudioDevice *)device;

- (void)onConnected:(id<JavaUtilList>)iceServers
              peers:(id<JavaUtilList>)peers;

- (void)onError:(jint)code
           data:(NSString *)data;

- (void)onErrorWithNSString:(NSString *)peerUid
                    withInt:(jint)code;

- (void)onIceCandidateWithNSString:(NSString *)peerUid
                withCFIceCandidate:(CFIceCandidate *)candidate;

- (void)onIceCandidatesRemovedWithNSString:(NSString *)peerUid
                     withJavaUtilArrayList:(JavaUtilArrayList *)candidates;

- (void)onIceConnectedWithNSString:(NSString *)peerUid;

- (void)onIceDisconnectedWithNSString:(NSString *)peerUid;

- (void)onLocalDescriptionWithNSString:(NSString *)peerUid
              withCFSessionDescription:(CFSessionDescription *)sdp;

- (void)onPause;

- (void)onPeerConnectionStatsReadyWithNSString:(NSString *)peerUid
                         withJavaUtilArrayList:(JavaUtilArrayList *)reports;

- (void)onPeerJoined:(NSString *)uid;

- (void)onPeerLeft:(NSString *)uid;

- (void)onPeerJoined:(NSString *)uid
               muted:(jboolean)muted;

- (void)onRemoteDescription:(NSString *)uid
                        sdp:(CFSessionDescription *)sdp;

- (void)onRemoteIceCandidate:(NSString *)uid
                   candidate:(CFIceCandidate *)candidate;

- (void)onRemoteIceCandidatesRemoved:(NSString *)uid
                          candidates:(id<JavaUtilList>)candidates;

- (void)onResume;

- (void)onStreamStarted:(NSString *)uid;

- (void)setAudioEnabled:(NSString *)uid
                enabled:(jboolean)enabled;

- (void)setVideoEnabled:(NSString *)uid
                enabled:(jboolean)enabled;

- (void)toggleFullscreen:(NSString *)uid;

#pragma mark Protected

- (id<CFRoomClient>)createRoomClient:(jboolean)wasMaster;

- (void)doDestroy;

- (void)doStartVideoSource;

- (void)doStopVideoSource;

- (void)java_finalize;

- (NSString *)getLaunchLogInfo;

- (jlong)getPreloadDuration;

- (void)preload:(jlong)rid;

- (void)preloadFinish;

#pragma mark Package-Private

- (void)doConfigure:(id<CFRoomClient>)roomClient
         guiWrapper:(id<CFGuiWrapper>)guiWrapper;

@end

J2OBJC_EMPTY_STATIC_INIT(CFAvConfShared)

J2OBJC_FIELD_SETTER(CFAvConfShared, mUid_, NSString *)
J2OBJC_FIELD_SETTER(CFAvConfShared, mConfig_, CFConfConfig *)
J2OBJC_FIELD_SETTER(CFAvConfShared, mConfEvents_, CFConfEvents *)
J2OBJC_FIELD_SETTER(CFAvConfShared, mExecutor_, id<JavaUtilConcurrentScheduledExecutorService>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mUiTaskRunner_, id<CFUiTaskRunner>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mAudioDeviceManager_, id<CFAudioDeviceManager>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mCpuMonitor_, id<CFCpuMonitor>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mPeers_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mStats_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mMutedPeers_, id<JavaUtilSet>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mLogger_, id<CFLogger>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mRoomClient_, id<CFRoomClient>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mPCClientFactory_, id<CFPeerConnectionClientFactory>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mGuiWrapper_, id<CFGuiWrapper>)
J2OBJC_FIELD_SETTER(CFAvConfShared, mIceServers_, id<JavaUtilList>)

inline NSString *CFAvConfShared_get_VERSION_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *CFAvConfShared_VERSION_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CFAvConfShared, VERSION_NAME, NSString *)

inline NSString *CFAvConfShared_get_TAG(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *CFAvConfShared_TAG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CFAvConfShared, TAG, NSString *)

FOUNDATION_EXPORT void CFAvConfShared_initWithUid_andConfig_andEvents_andLogger_andUiTaskRunner_andAudioDeviceManager_andCpuMonitor_(CFAvConfShared *self, NSString *uid, CFConfConfig *config, CFConfEventsBase *confEvents, id<CFLogger> logger, id<CFUiTaskRunner> uiTaskRunner, id<CFAudioDeviceManager> audioDeviceManager, id<CFCpuMonitor> cpuMonitor);

J2OBJC_TYPE_LITERAL_HEADER(CFAvConfShared)

@compatibility_alias ComPiasyAvconfAvConfShared CFAvConfShared;

#endif

#pragma pop_macro("INCLUDE_ALL_AvConfShared")
