//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/WebRTCAvConf-sources.jar!com/piasy/avconf/utils/LogUtil.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LogUtil")
#ifdef RESTRICT_LogUtil
#define INCLUDE_ALL_LogUtil 0
#else
#define INCLUDE_ALL_LogUtil 1
#endif
#undef RESTRICT_LogUtil

#if !defined (CFLogUtil_) && (INCLUDE_ALL_LogUtil || defined(INCLUDE_CFLogUtil))
#define CFLogUtil_

@interface CFLogUtil : NSObject

#pragma mark Public

+ (NSString *)confErr:(jint)code;

+ (NSString *)dir:(jint)dir;

+ (NSString *)mode:(jint)mode;

+ (NSString *)pcErr:(jint)code;

+ (NSString *)rsErr:(jint)code;

+ (NSString *)sdpType:(jint)type;

@end

J2OBJC_EMPTY_STATIC_INIT(CFLogUtil)

FOUNDATION_EXPORT NSString *CFLogUtil_mode_(jint mode);

FOUNDATION_EXPORT NSString *CFLogUtil_confErr_(jint code);

FOUNDATION_EXPORT NSString *CFLogUtil_pcErr_(jint code);

FOUNDATION_EXPORT NSString *CFLogUtil_rsErr_(jint code);

FOUNDATION_EXPORT NSString *CFLogUtil_dir_(jint dir);

FOUNDATION_EXPORT NSString *CFLogUtil_sdpType_(jint type);

J2OBJC_TYPE_LITERAL_HEADER(CFLogUtil)

@compatibility_alias ComPiasyAvconfUtilsLogUtil CFLogUtil;

#endif

#pragma pop_macro("INCLUDE_ALL_LogUtil")
