//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/WebRTCAvConf-sources.jar!com/github/piasy/avconf/api/PeerConnectionClient.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PeerConnectionClient")
#ifdef RESTRICT_PeerConnectionClient
#define INCLUDE_ALL_PeerConnectionClient 0
#else
#define INCLUDE_ALL_PeerConnectionClient 1
#endif
#undef RESTRICT_PeerConnectionClient

#if !defined (CFPeerConnectionClient_) && (INCLUDE_ALL_PeerConnectionClient || defined(INCLUDE_CFPeerConnectionClient))
#define CFPeerConnectionClient_

@class CFIceCandidate;
@protocol JavaUtilList;

@protocol CFPeerConnectionClient < JavaObject >

- (void)setPeerUid:(NSString *)peerUid;

- (void)preloadFinish;

- (void)setAudioSendingEnabled:(jboolean)enable;

- (void)setVideoSendingEnabled:(jboolean)enable;

- (jboolean)sending;

- (void)createOffer;

- (void)createAnswer;

- (void)addRemoteIceCandidate:(CFIceCandidate *)candidate;

- (void)removeRemoteIceCandidates:(id<JavaUtilList>)candidates;

- (void)setRemoteDescription:(jint)type
                         sdp:(NSString *)sdp;

- (void)setStatsEnable:(jboolean)enabled
              periodMs:(jint)periodMs;

- (jboolean)statsEnabled;

- (void)close;

@end

J2OBJC_EMPTY_STATIC_INIT(CFPeerConnectionClient)

inline jint CFPeerConnectionClient_get_SDP_TYPE_UNKNOWN(void);
#define CFPeerConnectionClient_SDP_TYPE_UNKNOWN -1
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClient, SDP_TYPE_UNKNOWN, jint)

inline jint CFPeerConnectionClient_get_SDP_TYPE_OFFER(void);
#define CFPeerConnectionClient_SDP_TYPE_OFFER 0
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClient, SDP_TYPE_OFFER, jint)

inline jint CFPeerConnectionClient_get_SDP_TYPE_PRANSWER(void);
#define CFPeerConnectionClient_SDP_TYPE_PRANSWER 1
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClient, SDP_TYPE_PRANSWER, jint)

inline jint CFPeerConnectionClient_get_SDP_TYPE_ANSWER(void);
#define CFPeerConnectionClient_SDP_TYPE_ANSWER 2
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClient, SDP_TYPE_ANSWER, jint)

inline NSString *CFPeerConnectionClient_get_VIDEO_TRACK_ID(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *CFPeerConnectionClient_VIDEO_TRACK_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CFPeerConnectionClient, VIDEO_TRACK_ID, NSString *)

inline NSString *CFPeerConnectionClient_get_AUDIO_TRACK_ID(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *CFPeerConnectionClient_AUDIO_TRACK_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CFPeerConnectionClient, AUDIO_TRACK_ID, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(CFPeerConnectionClient)

#define ComGithubPiasyAvconfApiPeerConnectionClient CFPeerConnectionClient

#endif

#if !defined (CFPeerConnectionClientFactory_) && (INCLUDE_ALL_PeerConnectionClient || defined(INCLUDE_CFPeerConnectionClientFactory))
#define CFPeerConnectionClientFactory_

@protocol CFPeerConnectionClient;
@protocol JavaUtilList;

@protocol CFPeerConnectionClientFactory < JavaObject >

- (void)createLocalVideoTrack:(id)localVideoRenderer;

- (void)createLocalAudioTrack;

- (id<CFPeerConnectionClient>)createPeerConnectionClient:(NSString *)peerUid
                                              iceServers:(id<JavaUtilList>)iceServers
                                                    send:(jboolean)send
                                                 receive:(jboolean)receive
                                                 preload:(jboolean)preload;

@end

J2OBJC_EMPTY_STATIC_INIT(CFPeerConnectionClientFactory)

J2OBJC_TYPE_LITERAL_HEADER(CFPeerConnectionClientFactory)

#endif

#if !defined (CFPeerConnectionClientCallback_) && (INCLUDE_ALL_PeerConnectionClient || defined(INCLUDE_CFPeerConnectionClientCallback))
#define CFPeerConnectionClientCallback_

@class CFIceCandidate;
@protocol JavaUtilList;

@protocol CFPeerConnectionClientCallback < JavaObject >

- (void)onLocalDescription:(NSString *)peerUid
                      type:(jint)type
                       sdp:(NSString *)sdp;

- (void)onIceCandidate:(NSString *)peerUid
             candidate:(CFIceCandidate *)candidate;

- (void)onIceCandidatesRemoved:(NSString *)peerUid
                    candidates:(id<JavaUtilList>)candidates;

- (void)onIceConnected:(NSString *)peerUid;

- (void)onIceDisconnected:(NSString *)peerUid;

- (void)onPeerConnectionClosed:(NSString *)peerUid;

- (void)onPeerConnectionStatsReady:(NSString *)peerUid
                           reports:(id<JavaUtilList>)reports;

- (void)onPeerConnectionError:(NSString *)peerUid
                  description:(NSString *)description_;

@end

J2OBJC_EMPTY_STATIC_INIT(CFPeerConnectionClientCallback)

J2OBJC_TYPE_LITERAL_HEADER(CFPeerConnectionClientCallback)

#endif

#pragma pop_macro("INCLUDE_ALL_PeerConnectionClient")
