//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/pc_client_api-sources.jar!com/piasy/avconf/PeerConnectionClientApi.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PeerConnectionClientApi")
#ifdef RESTRICT_PeerConnectionClientApi
#define INCLUDE_ALL_PeerConnectionClientApi 0
#else
#define INCLUDE_ALL_PeerConnectionClientApi 1
#endif
#undef RESTRICT_PeerConnectionClientApi

#if !defined (CFPeerConnectionClientApi_) && (INCLUDE_ALL_PeerConnectionClientApi || defined(INCLUDE_CFPeerConnectionClientApi))
#define CFPeerConnectionClientApi_

@class CFIceCandidate;
@class CFNativeRenderer;
@class CFPeerConnectionClientCallback;
@class CFSessionDescription;
@class JavaUtilArrayList;

@interface CFPeerConnectionClientApi : NSObject

#pragma mark Public

- (instancetype)init;

- (void)addIceCandidateWithCFIceCandidate:(CFIceCandidate *)candidate;

- (void)close;

+ (CFPeerConnectionClientApi *)createWithNSString:(NSString *)peerUid
                                          withInt:(jint)dir
               withCFPeerConnectionClientCallback:(CFPeerConnectionClientCallback *)callback
                             withCFNativeRenderer:(CFNativeRenderer *)remoteTrackRenderer
                                      withBoolean:(jboolean)preload
                                          withInt:(jint)startBitrate;

- (void)createAnswer;

- (void)createOffer;

- (void)createPeerConnectionWithJavaUtilArrayList:(JavaUtilArrayList *)iceServers;

- (void)enableStatsEventsWithBoolean:(jboolean)enable
                             withInt:(jint)periodMs;

- (void)finishPreload;

- (jboolean)receive;

- (void)removeIceCandidatesWithJavaUtilArrayList:(JavaUtilArrayList *)candidates;

- (jboolean)send;

- (void)setAudioReceivingEnabledWithBoolean:(jboolean)enable;

- (void)setAudioSendingEnabledWithBoolean:(jboolean)enable;

- (void)setRemoteDescriptionWithCFSessionDescription:(CFSessionDescription *)sdp;

- (void)setVideoReceivingEnabledWithBoolean:(jboolean)enable;

- (void)setVideoSendingEnabledWithBoolean:(jboolean)enable;

- (jboolean)statsEnabled;

@end

J2OBJC_EMPTY_STATIC_INIT(CFPeerConnectionClientApi)

inline jint CFPeerConnectionClientApi_get_DIR_INACTIVE(void);
#define CFPeerConnectionClientApi_DIR_INACTIVE 0
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientApi, DIR_INACTIVE, jint)

inline jint CFPeerConnectionClientApi_get_DIR_RECV_ONLY(void);
#define CFPeerConnectionClientApi_DIR_RECV_ONLY 1
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientApi, DIR_RECV_ONLY, jint)

inline jint CFPeerConnectionClientApi_get_DIR_SEND_ONLY(void);
#define CFPeerConnectionClientApi_DIR_SEND_ONLY 2
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientApi, DIR_SEND_ONLY, jint)

inline jint CFPeerConnectionClientApi_get_DIR_SEND_RECV(void);
#define CFPeerConnectionClientApi_DIR_SEND_RECV 3
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientApi, DIR_SEND_RECV, jint)

inline NSString *CFPeerConnectionClientApi_get_K_AUDIO_TRACK_ID(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *CFPeerConnectionClientApi_K_AUDIO_TRACK_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CFPeerConnectionClientApi, K_AUDIO_TRACK_ID, NSString *)

inline NSString *CFPeerConnectionClientApi_get_K_VIDEO_TRACK_ID(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *CFPeerConnectionClientApi_K_VIDEO_TRACK_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CFPeerConnectionClientApi, K_VIDEO_TRACK_ID, NSString *)

inline NSString *CFPeerConnectionClientApi_get_K_STREAM_ID(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *CFPeerConnectionClientApi_K_STREAM_ID;
J2OBJC_STATIC_FIELD_OBJ_FINAL(CFPeerConnectionClientApi, K_STREAM_ID, NSString *)

inline jint CFPeerConnectionClientApi_get_K_BPS_IN_KBPS(void);
#define CFPeerConnectionClientApi_K_BPS_IN_KBPS 1000
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientApi, K_BPS_IN_KBPS, jint)

FOUNDATION_EXPORT void CFPeerConnectionClientApi_init(CFPeerConnectionClientApi *self);

FOUNDATION_EXPORT CFPeerConnectionClientApi *CFPeerConnectionClientApi_createWithNSString_withInt_withCFPeerConnectionClientCallback_withCFNativeRenderer_withBoolean_withInt_(NSString *peerUid, jint dir, CFPeerConnectionClientCallback *callback, CFNativeRenderer *remoteTrackRenderer, jboolean preload, jint startBitrate);

J2OBJC_TYPE_LITERAL_HEADER(CFPeerConnectionClientApi)

@compatibility_alias ComPiasyAvconfPeerConnectionClientApi CFPeerConnectionClientApi;

#endif

#pragma pop_macro("INCLUDE_ALL_PeerConnectionClientApi")
