//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/pc_client_api-sources.jar!com/piasy/avconf/PeerConnectionClientCallback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PeerConnectionClientCallback")
#ifdef RESTRICT_PeerConnectionClientCallback
#define INCLUDE_ALL_PeerConnectionClientCallback 0
#else
#define INCLUDE_ALL_PeerConnectionClientCallback 1
#endif
#undef RESTRICT_PeerConnectionClientCallback

#if !defined (CFPeerConnectionClientCallback_) && (INCLUDE_ALL_PeerConnectionClientCallback || defined(INCLUDE_CFPeerConnectionClientCallback))
#define CFPeerConnectionClientCallback_

@class CFIceCandidate;
@class CFSessionDescription;
@class JavaUtilArrayList;

@interface CFPeerConnectionClientCallback : NSObject

#pragma mark Public

- (instancetype)init;

- (void)onErrorWithNSString:(NSString *)peerUid
                    withInt:(jint)code;

- (void)onIceCandidateWithNSString:(NSString *)peerUid
                withCFIceCandidate:(CFIceCandidate *)candidate;

- (void)onIceCandidatesRemovedWithNSString:(NSString *)peerUid
                     withJavaUtilArrayList:(JavaUtilArrayList *)candidates;

- (void)onIceConnectedWithNSString:(NSString *)peerUid;

- (void)onIceDisconnectedWithNSString:(NSString *)peerUid;

- (void)onLocalDescriptionWithNSString:(NSString *)peerUid
              withCFSessionDescription:(CFSessionDescription *)localSdp;

- (void)onPeerConnectionStatsReadyWithNSString:(NSString *)peerUid
                         withJavaUtilArrayList:(JavaUtilArrayList *)reports;

@end

J2OBJC_EMPTY_STATIC_INIT(CFPeerConnectionClientCallback)

inline jint CFPeerConnectionClientCallback_get_ERR_NO_FACTORY(void);
#define CFPeerConnectionClientCallback_ERR_NO_FACTORY 1000
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientCallback, ERR_NO_FACTORY, jint)

inline jint CFPeerConnectionClientCallback_get_ERR_NO_SENDING_TRACK(void);
#define CFPeerConnectionClientCallback_ERR_NO_SENDING_TRACK 1001
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientCallback, ERR_NO_SENDING_TRACK, jint)

inline jint CFPeerConnectionClientCallback_get_ERR_CREATE_PC_FAIL(void);
#define CFPeerConnectionClientCallback_ERR_CREATE_PC_FAIL 1002
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientCallback, ERR_CREATE_PC_FAIL, jint)

inline jint CFPeerConnectionClientCallback_get_ERR_ICE_FAIL(void);
#define CFPeerConnectionClientCallback_ERR_ICE_FAIL 1003
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientCallback, ERR_ICE_FAIL, jint)

inline jint CFPeerConnectionClientCallback_get_ERR_CREATE_MULTIPLE_SDP(void);
#define CFPeerConnectionClientCallback_ERR_CREATE_MULTIPLE_SDP 1004
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientCallback, ERR_CREATE_MULTIPLE_SDP, jint)

inline jint CFPeerConnectionClientCallback_get_ERR_CREATE_SDP_FAIL(void);
#define CFPeerConnectionClientCallback_ERR_CREATE_SDP_FAIL 1005
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientCallback, ERR_CREATE_SDP_FAIL, jint)

inline jint CFPeerConnectionClientCallback_get_ERR_SET_SDP_FAIL(void);
#define CFPeerConnectionClientCallback_ERR_SET_SDP_FAIL 1006
J2OBJC_STATIC_FIELD_CONSTANT(CFPeerConnectionClientCallback, ERR_SET_SDP_FAIL, jint)

FOUNDATION_EXPORT void CFPeerConnectionClientCallback_init(CFPeerConnectionClientCallback *self);

J2OBJC_TYPE_LITERAL_HEADER(CFPeerConnectionClientCallback)

@compatibility_alias ComPiasyAvconfPeerConnectionClientCallback CFPeerConnectionClientCallback;

#endif

#pragma pop_macro("INCLUDE_ALL_PeerConnectionClientCallback")
