//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/WebRTCAvConf-sources.jar!com/piasy/avconf/api/RoomClient.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RoomClient")
#ifdef RESTRICT_RoomClient
#define INCLUDE_ALL_RoomClient 0
#else
#define INCLUDE_ALL_RoomClient 1
#endif
#undef RESTRICT_RoomClient

#if !defined (CFRoomClient_) && (INCLUDE_ALL_RoomClient || defined(INCLUDE_CFRoomClient))
#define CFRoomClient_

@class CFIceCandidate;
@class CFSessionDescription;
@protocol CFAsyncOpCallback;
@protocol JavaUtilList;

@protocol CFRoomClient < JavaObject >

- (void)connect:(NSString *)rsUrl
         roomId:(jlong)roomId;

- (void)sendSdp:(NSString *)uid
            sdp:(CFSessionDescription *)sdp;

- (void)sendLocalIceCandidate:(NSString *)uid
                    candidate:(CFIceCandidate *)candidate;

- (void)sendLocalIceCandidateRemovals:(NSString *)uid
                           candidates:(id<JavaUtilList>)candidates;

- (void)setAudioEnabled:(jboolean)enabled;

- (void)setVideoEnabled:(jboolean)enabled;

- (void)setAllowJoin:(jboolean)allowJoin
            callback:(id<CFAsyncOpCallback>)callback;

- (void)createPublisher;

- (jboolean)isMaster;

- (void)disconnect:(jboolean)destroyRoom
           onClose:(id<CFAsyncOpCallback>)onClose;

@end

J2OBJC_EMPTY_STATIC_INIT(CFRoomClient)

J2OBJC_TYPE_LITERAL_HEADER(CFRoomClient)

#define ComPiasyAvconfApiRoomClient CFRoomClient

#endif

#if !defined (CFRoomClientCallback_) && (INCLUDE_ALL_RoomClient || defined(INCLUDE_CFRoomClientCallback))
#define CFRoomClientCallback_

@class CFIceCandidate;
@class CFSessionDescription;
@protocol JavaUtilList;

@protocol CFRoomClientCallback < JavaObject >

- (void)onConnected:(id<JavaUtilList>)iceServers
              peers:(id<JavaUtilList>)peers;

- (void)onStreamStarted:(NSString *)uid;

- (void)onPeerJoined:(NSString *)uid;

- (void)onPeerJoined:(NSString *)uid
               muted:(jboolean)muted;

- (void)onRemoteDescription:(NSString *)uid
                        sdp:(CFSessionDescription *)sdp;

- (void)onRemoteIceCandidate:(NSString *)uid
                   candidate:(CFIceCandidate *)candidate;

- (void)onRemoteIceCandidatesRemoved:(NSString *)uid
                          candidates:(id<JavaUtilList>)candidates;

- (void)onPeerLeft:(NSString *)uid;

- (void)onError:(jint)code
           data:(NSString *)data;

@end

J2OBJC_EMPTY_STATIC_INIT(CFRoomClientCallback)

inline jint CFRoomClientCallback_get_ERR_RS_FAILURE(void);
#define CFRoomClientCallback_ERR_RS_FAILURE 1001
J2OBJC_STATIC_FIELD_CONSTANT(CFRoomClientCallback, ERR_RS_FAILURE, jint)

inline jint CFRoomClientCallback_get_ERR_ICE_FAILURE(void);
#define CFRoomClientCallback_ERR_ICE_FAILURE 1002
J2OBJC_STATIC_FIELD_CONSTANT(CFRoomClientCallback, ERR_ICE_FAILURE, jint)

inline jint CFRoomClientCallback_get_ERR_ROOM_DESTROYED(void);
#define CFRoomClientCallback_ERR_ROOM_DESTROYED 1003
J2OBJC_STATIC_FIELD_CONSTANT(CFRoomClientCallback, ERR_ROOM_DESTROYED, jint)

inline jint CFRoomClientCallback_get_ERR_NO_PUBLISHER(void);
#define CFRoomClientCallback_ERR_NO_PUBLISHER 1004
J2OBJC_STATIC_FIELD_CONSTANT(CFRoomClientCallback, ERR_NO_PUBLISHER, jint)

J2OBJC_TYPE_LITERAL_HEADER(CFRoomClientCallback)

#endif

#pragma pop_macro("INCLUDE_ALL_RoomClient")
