//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/WebRTCAvConf-sources.jar!com/piasy/avconf/ConfConfig.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ConfConfig")
#ifdef RESTRICT_ConfConfig
#define INCLUDE_ALL_ConfConfig 0
#else
#define INCLUDE_ALL_ConfConfig 1
#endif
#undef RESTRICT_ConfConfig

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (CFConfConfig_) && (INCLUDE_ALL_ConfConfig || defined(INCLUDE_CFConfConfig))
#define CFConfConfig_

@class CFConfConfigBuilder;
@class CFConfConfigExtras;

@interface CFConfConfig : NSObject

#pragma mark Public

- (instancetype)init;

+ (CFConfConfigBuilder *)builder;

- (CFConfConfigExtras *)extras;

- (jint)keep_alive_interval;

- (jint)max_peers;

- (jint)mode;

- (NSString *)recording_file_name;

- (jboolean)recording_self;

- (jboolean)recording_whole_room;

- (jint)retry_times;

- (jint)room_auto_destroy_size;

- (jint)rs_connect_timeout;

- (NSString *)rs_url;

- (jint)start_bitrate;

- (jint)video_capture_height;

- (jint)video_capture_width;

- (jint)video_codec;

- (jint)video_fps;

- (jint)video_publish_height;

- (jint)video_publish_width;

- (jint)video_render_scale_type;

@end

J2OBJC_EMPTY_STATIC_INIT(CFConfConfig)

inline jint CFConfConfig_get_DEFAULT_START_BITRATE(void);
#define CFConfConfig_DEFAULT_START_BITRATE 800
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, DEFAULT_START_BITRATE, jint)

inline jint CFConfConfig_get_MODE_APPRTC(void);
#define CFConfConfig_MODE_APPRTC 0
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, MODE_APPRTC, jint)

inline jint CFConfConfig_get_MODE_JANUS_VIDEO_ROOM(void);
#define CFConfConfig_MODE_JANUS_VIDEO_ROOM 1
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, MODE_JANUS_VIDEO_ROOM, jint)

inline jint CFConfConfig_get_SCALE_TYPE_CENTER_CROP(void);
#define CFConfConfig_SCALE_TYPE_CENTER_CROP 1
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, SCALE_TYPE_CENTER_CROP, jint)

inline jint CFConfConfig_get_SCALE_TYPE_CENTER_INSIDE(void);
#define CFConfConfig_SCALE_TYPE_CENTER_INSIDE 2
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, SCALE_TYPE_CENTER_INSIDE, jint)

inline jint CFConfConfig_get_VIDEO_CODEC_VP8(void);
#define CFConfConfig_VIDEO_CODEC_VP8 1
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, VIDEO_CODEC_VP8, jint)

inline jint CFConfConfig_get_VIDEO_CODEC_VP9(void);
#define CFConfConfig_VIDEO_CODEC_VP9 2
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, VIDEO_CODEC_VP9, jint)

inline jint CFConfConfig_get_VIDEO_CODEC_H264_BASELINE(void);
#define CFConfConfig_VIDEO_CODEC_H264_BASELINE 3
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, VIDEO_CODEC_H264_BASELINE, jint)

inline jint CFConfConfig_get_VIDEO_CODEC_H264_HIGH_PROFILE(void);
#define CFConfConfig_VIDEO_CODEC_H264_HIGH_PROFILE 4
J2OBJC_STATIC_FIELD_CONSTANT(CFConfConfig, VIDEO_CODEC_H264_HIGH_PROFILE, jint)

FOUNDATION_EXPORT void CFConfConfig_init(CFConfConfig *self);

FOUNDATION_EXPORT CFConfConfigBuilder *CFConfConfig_builder(void);

J2OBJC_TYPE_LITERAL_HEADER(CFConfConfig)

@compatibility_alias ComPiasyAvconfConfConfig CFConfConfig;

#endif

#if !defined (CFConfConfigBuilder_) && (INCLUDE_ALL_ConfConfig || defined(INCLUDE_CFConfConfigBuilder))
#define CFConfConfigBuilder_

@class CFConfConfig;
@class CFConfConfigExtras;

@interface CFConfConfigBuilder : NSObject

#pragma mark Public

- (instancetype)init;

- (CFConfConfig *)build;

- (CFConfConfigBuilder *)extras:(CFConfConfigExtras *)extras;

- (CFConfConfigBuilder *)keep_alive_interval:(jint)keep_alive_interval;

- (CFConfConfigBuilder *)max_peers:(jint)max_peers;

- (CFConfConfigBuilder *)mode:(jint)mode;

- (CFConfConfigBuilder *)recording_file_name:(NSString *)recording_file_name;

- (CFConfConfigBuilder *)recording_self:(jboolean)recording_self;

- (CFConfConfigBuilder *)recording_whole_room:(jboolean)recording_whole_room;

- (CFConfConfigBuilder *)retry_times:(jint)rs_retry_times;

- (CFConfConfigBuilder *)room_auto_destroy_size:(jint)room_auto_destroy_size;

- (CFConfConfigBuilder *)rs_connect_timeout:(jint)rs_connect_timeout;

- (CFConfConfigBuilder *)rs_url:(NSString *)rs_url;

- (CFConfConfigBuilder *)start_bitrate:(jint)start_bitrate;

- (CFConfConfigBuilder *)video_capture_height:(jint)video_capture_height;

- (CFConfConfigBuilder *)video_capture_width:(jint)video_capture_width;

- (CFConfConfigBuilder *)video_codec:(jint)video_codec;

- (CFConfConfigBuilder *)video_fps:(jint)video_fps;

- (CFConfConfigBuilder *)video_publish_height:(jint)video_publish_height;

- (CFConfConfigBuilder *)video_publish_width:(jint)video_publish_width;

- (CFConfConfigBuilder *)video_render_scale_type:(jint)video_render_scale_type;

@end

J2OBJC_EMPTY_STATIC_INIT(CFConfConfigBuilder)

FOUNDATION_EXPORT void CFConfConfigBuilder_init(CFConfConfigBuilder *self);

J2OBJC_TYPE_LITERAL_HEADER(CFConfConfigBuilder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ConfConfig")
