//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/WebRTCAvConf-sources.jar!com/piasy/avconf/ConfEventsBase.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ConfEventsBase")
#ifdef RESTRICT_ConfEventsBase
#define INCLUDE_ALL_ConfEventsBase 0
#else
#define INCLUDE_ALL_ConfEventsBase 1
#endif
#undef RESTRICT_ConfEventsBase

#if !defined (CFConfEventsBase_) && (INCLUDE_ALL_ConfEventsBase || defined(INCLUDE_CFConfEventsBase))
#define CFConfEventsBase_

@interface CFConfEventsBase : NSObject

#pragma mark Public

- (instancetype)init;

- (void)onDestroyed;

- (void)onErrorWithInt:(jint)code
          withNSString:(NSString *)data;

- (void)onPeerJoinedWithNSString:(NSString *)uid;

- (void)onPeerLeftWithNSString:(NSString *)uid;

- (void)onPeerMutedWithNSString:(NSString *)uid
                    withBoolean:(jboolean)muted;

- (void)onPreloadFinished;

- (void)onStreamStartedWithNSString:(NSString *)uid;

@end

J2OBJC_EMPTY_STATIC_INIT(CFConfEventsBase)

inline jint CFConfEventsBase_get_ERR_INIT_FAIL(void);
#define CFConfEventsBase_ERR_INIT_FAIL 1001
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_INIT_FAIL, jint)

inline jint CFConfEventsBase_get_ERR_RS_FAIL(void);
#define CFConfEventsBase_ERR_RS_FAIL 1002
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_RS_FAIL, jint)

inline jint CFConfEventsBase_get_ERR_PC_FAIL(void);
#define CFConfEventsBase_ERR_PC_FAIL 1003
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_PC_FAIL, jint)

inline jint CFConfEventsBase_get_ERR_FULL(void);
#define CFConfEventsBase_ERR_FULL 1004
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_FULL, jint)

inline jint CFConfEventsBase_get_ERR_UNAUTHORIZED(void);
#define CFConfEventsBase_ERR_UNAUTHORIZED 1005
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_UNAUTHORIZED, jint)

inline jint CFConfEventsBase_get_ERR_ROOM_DESTROYED(void);
#define CFConfEventsBase_ERR_ROOM_DESTROYED 1006
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_ROOM_DESTROYED, jint)

inline jint CFConfEventsBase_get_ERR_VIDEO_CAPTURER_FAIL(void);
#define CFConfEventsBase_ERR_VIDEO_CAPTURER_FAIL 1101
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_VIDEO_CAPTURER_FAIL, jint)

inline jint CFConfEventsBase_get_ERR_DISABLE_BOTH_AUDIO_AND_VIDEO(void);
#define CFConfEventsBase_ERR_DISABLE_BOTH_AUDIO_AND_VIDEO 2001
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_DISABLE_BOTH_AUDIO_AND_VIDEO, jint)

inline jint CFConfEventsBase_get_ERR_RETRYING(void);
#define CFConfEventsBase_ERR_RETRYING 2002
J2OBJC_STATIC_FIELD_CONSTANT(CFConfEventsBase, ERR_RETRYING, jint)

FOUNDATION_EXPORT void CFConfEventsBase_init(CFConfEventsBase *self);

J2OBJC_TYPE_LITERAL_HEADER(CFConfEventsBase)

@compatibility_alias ComPiasyAvconfConfEventsBase CFConfEventsBase;

#endif

#pragma pop_macro("INCLUDE_ALL_ConfEventsBase")
