//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/WebRTCAvConf-sources.jar!com/piasy/avconf/api/PeerConnectionClientFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PeerConnectionClientFactory")
#ifdef RESTRICT_PeerConnectionClientFactory
#define INCLUDE_ALL_PeerConnectionClientFactory 0
#else
#define INCLUDE_ALL_PeerConnectionClientFactory 1
#endif
#undef RESTRICT_PeerConnectionClientFactory

#if !defined (CFPeerConnectionClientFactory_) && (INCLUDE_ALL_PeerConnectionClientFactory || defined(INCLUDE_CFPeerConnectionClientFactory))
#define CFPeerConnectionClientFactory_

@class CFPeerConnectionClientApi;

@protocol CFPeerConnectionClientFactory < JavaObject >

- (void)createLocalTracks:(id)localVideoRenderer;

- (CFPeerConnectionClientApi *)createPeerConnectionClient:(NSString *)peerUid
                                                      dir:(jint)dir
                                                  preload:(jboolean)preload;

@end

J2OBJC_EMPTY_STATIC_INIT(CFPeerConnectionClientFactory)

J2OBJC_TYPE_LITERAL_HEADER(CFPeerConnectionClientFactory)

#define ComPiasyAvconfApiPeerConnectionClientFactory CFPeerConnectionClientFactory

#endif

#pragma pop_macro("INCLUDE_ALL_PeerConnectionClientFactory")
